#!/usr/bin/env bash

# scrict mode
set -o errexit -o nounset -o pipefail
IFS=$'\n\t'

PROFILE=""
PROFILE_FILE=""

usage() {
  declare -a lines=(
    "Synopsis:"
    "  This is a wrapper to call tintin++ using a 'profile' file in profiles/."
    ""
    "Options:"
    "  -h this message"
    ""
    "Examples"
    "  $0 foo_bar # play 3k with the foo_bar profile"
  )
  for line in "${lines[@]}"; do echo "${line}"; done
}

valid_profiles() {
  printf "Valid profile : guild for profile:\n"

  for profile in $(ls profiles/*.tin | grep -v profile_example); do
    local profile_name=$(echo ${profile} | sed 's/.tin//' | sed 's/profiles\///')
    local guild=$(grep 'var guild ' ${profile} | sed 's/.*{//' | sed 's/};//')
    echo "  ${profile_name} : ${guild}"
  done
}

while getopts 'h:' opt; do
  case "${opt}" in
    h)
      usage
      exit 0
      ;;
  esac
done

if [ $# -gt 0 ]; then
  PROFILE=$1
  PROFILE_FILE=${PROFILE}.tin
  if [ -f "profiles/${PROFILE_FILE}" ]; then
    rm -f tin/map/map_globals.txt
    PROFILE=${PROFILE} tt++ profiles/${PROFILE_FILE}
  fi
else
  printf "Need a valid profile name.\n\n"
  valid_profiles
  echo
  usage
  exit 1
fi
