#!/usr/bin/env bash

##
 # for this to work we have to export this var to all sessions...
 # might need to use a file instead
 ##
MAP_DIR="tin/map"

# set width if passed
if [[ "$1" =~ ^[0-9]+$ ]] && [ 0 -le "$1" ]; then
  echo setting width to $1
  echo width:$1 > "${MAP_DIR}/map_globals.txt"
fi

# set height if passed
if [[ "$2" =~ ^[0-9]+$ ]] && [ 0 -le "$1" ]; then
  echo setting height to $2
  echo height:$2 >> "${MAP_DIR}/map_globals.txt"
fi

##
 # tail the map so it refreshes; try to use -s option if available to refresh
 # constantly
 ##
if $(tail -s 0 /dev/null 2> /dev/null); then
  tail -f -s 0 "${MAP_DIR}/current_map.txt" 2> /dev/null
else
  tail -f "${MAP_DIR}/current_map.txt" 2> /dev/null
fi
